// <auto-generated />
using System;
using BlazorMilk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorMilk.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251114063015_TrySyncClients")]
    partial class TrySyncClients
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("BlazorMilk.Models.client", b =>
                {
                    b.Property<int>("idClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("idClient")
                        .HasName("PRIMARY");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("BlazorMilk.Models.detailofproductmaterial", b =>
                {
                    b.Property<int>("idMaterial")
                        .HasColumnType("int");

                    b.Property<int>("idOrderDetails")
                        .HasColumnType("int");

                    b.Property<int>("idProduct")
                        .HasColumnType("int");

                    b.HasKey("idMaterial", "idOrderDetails", "idProduct")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0, 0 });

                    b.HasIndex(new[] { "idMaterial" }, "fk_material_has_orderdetails_material1_idx");

                    b.HasIndex(new[] { "idOrderDetails" }, "fk_material_has_orderdetails_orderdetails1_idx");

                    b.HasIndex(new[] { "idProduct" }, "fk_materialoforder_product1_idx");

                    b.ToTable("detailofproductmaterial", (string)null);
                });

            modelBuilder.Entity("BlazorMilk.Models.material", b =>
                {
                    b.Property<int>("idMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Идентификатор материала");

                    b.Property<string>("codeMaterial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Код материала");

                    b.Property<double>("countMaterial")
                        .HasColumnType("double")
                        .HasComment("Количество материала");

                    b.Property<string>("nameMaterial")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasComment("Название материала");

                    b.Property<double>("priceMaterial")
                        .HasColumnType("double")
                        .HasComment("Цена материала");

                    b.Property<string>("systemMaterial")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasComment("Система счисления материала (кг, г)");

                    b.HasKey("idMaterial")
                        .HasName("PRIMARY");

                    b.ToTable("material", (string)null);

                    b.HasComment("Материал");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("BlazorMilk.Models.orderdetail", b =>
                {
                    b.Property<int>("idOrderDetails")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("countProduct")
                        .HasColumnType("int");

                    b.Property<DateOnly>("dateOrder")
                        .HasColumnType("date");

                    b.Property<int>("idOrder")
                        .HasColumnType("int");

                    b.Property<string>("nameProduct")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<double>("priceDetail")
                        .HasColumnType("double");

                    b.Property<string>("systemProduct")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.HasKey("idOrderDetails")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "idOrder" }, "fk_orderdetails_ordervendor1_idx");

                    b.ToTable("orderdetails");
                });

            modelBuilder.Entity("BlazorMilk.Models.ordervendor", b =>
                {
                    b.Property<int>("idOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("customer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Заказчик");

                    b.Property<string>("executor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Исполнитель");

                    b.Property<string>("idVendor")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasComment("Айди вендора")
                        .UseCollation("utf8mb4_bin");

                    b.Property<double?>("total")
                        .HasColumnType("double")
                        .HasComment("Итого");

                    b.HasKey("idOrder")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "idVendor" }, "fk_Order_Vendor1_idx");

                    b.ToTable("ordervendor", (string)null);

                    b.HasComment("Заказ от вендора");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("BlazorMilk.Models.product", b =>
                {
                    b.Property<int>("idProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Идентификатор продукта");

                    b.Property<string>("codeProduct")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Код продукта");

                    b.Property<double>("countProduct")
                        .HasColumnType("double")
                        .HasComment("Количество продукта");

                    b.Property<string>("nameProduct")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasComment("Название продукта");

                    b.Property<double>("percentProduct")
                        .HasColumnType("double")
                        .HasComment("Процент продукта (Сметана 15%)");

                    b.Property<double>("priceProduct")
                        .HasColumnType("double")
                        .HasComment("Цена продукта");

                    b.Property<string>("systemProduct")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasComment("Система счисления продукта (кг, г)");

                    b.Property<double>("weightProduct")
                        .HasColumnType("double")
                        .HasComment("Вес продукта");

                    b.HasKey("idProduct")
                        .HasName("PRIMARY");

                    b.ToTable("product", (string)null);

                    b.HasComment("Продукт");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("BlazorMilk.Models.vendor", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasComment("Идентификатор в строковом виде")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("addressVendor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Адрес вендора ");

                    b.Property<sbyte>("buyer")
                        .HasColumnType("tinyint")
                        .HasComment("Покупатель");

                    b.Property<string>("innVendor")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasComment("ИНН вендора");

                    b.Property<string>("nameVendor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Имя вендора");

                    b.Property<string>("phoneVendor")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasComment("Телефон вендора");

                    b.Property<sbyte>("salesman")
                        .HasColumnType("tinyint")
                        .HasComment("Продавец");

                    b.HasKey("id");

                    b.ToTable("vendor", (string)null);

                    b.HasComment("Вендор (заинтересованные лица)");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("BlazorMilk.Models.vproductscount", b =>
                {
                    b.Property<decimal?>("countProduct")
                        .HasPrecision(32)
                        .HasColumnType("decimal(32)");

                    b.ToView("vproductscount");
                });

            modelBuilder.Entity("BlazorMilk.Models.vtotalproduct", b =>
                {
                    b.Property<double?>("Total")
                        .HasColumnType("double(22,0)");

                    b.ToView("vtotalproducts");
                });

            modelBuilder.Entity("BlazorMilk.Models.detailofproductmaterial", b =>
                {
                    b.HasOne("BlazorMilk.Models.material", "idMaterialNavigation")
                        .WithMany("detailofproductmaterials")
                        .HasForeignKey("idMaterial")
                        .IsRequired()
                        .HasConstraintName("fk_material_has_orderdetails_material1");

                    b.HasOne("BlazorMilk.Models.orderdetail", "idOrderDetailsNavigation")
                        .WithMany("detailofproductmaterials")
                        .HasForeignKey("idOrderDetails")
                        .IsRequired()
                        .HasConstraintName("fk_material_has_orderdetails_orderdetails1");

                    b.HasOne("BlazorMilk.Models.product", "idProductNavigation")
                        .WithMany("detailofproductmaterials")
                        .HasForeignKey("idProduct")
                        .IsRequired()
                        .HasConstraintName("fk_materialoforder_product1");

                    b.Navigation("idMaterialNavigation");

                    b.Navigation("idOrderDetailsNavigation");

                    b.Navigation("idProductNavigation");
                });

            modelBuilder.Entity("BlazorMilk.Models.orderdetail", b =>
                {
                    b.HasOne("BlazorMilk.Models.ordervendor", "idOrderNavigation")
                        .WithMany("orderdetails")
                        .HasForeignKey("idOrder")
                        .IsRequired()
                        .HasConstraintName("fk_orderdetails_ordervendor1");

                    b.Navigation("idOrderNavigation");
                });

            modelBuilder.Entity("BlazorMilk.Models.ordervendor", b =>
                {
                    b.HasOne("BlazorMilk.Models.vendor", "idVendorNavigation")
                        .WithMany("ordervendors")
                        .HasForeignKey("idVendor")
                        .IsRequired()
                        .HasConstraintName("fk_Order_Vendor1");

                    b.Navigation("idVendorNavigation");
                });

            modelBuilder.Entity("BlazorMilk.Models.material", b =>
                {
                    b.Navigation("detailofproductmaterials");
                });

            modelBuilder.Entity("BlazorMilk.Models.orderdetail", b =>
                {
                    b.Navigation("detailofproductmaterials");
                });

            modelBuilder.Entity("BlazorMilk.Models.ordervendor", b =>
                {
                    b.Navigation("orderdetails");
                });

            modelBuilder.Entity("BlazorMilk.Models.product", b =>
                {
                    b.Navigation("detailofproductmaterials");
                });

            modelBuilder.Entity("BlazorMilk.Models.vendor", b =>
                {
                    b.Navigation("ordervendors");
                });
#pragma warning restore 612, 618
        }
    }
}
